version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stajprojesi
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-riza1907}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET:-VGhpcyBpcyBhIHZlcnkgc3VwZXIgc2VjcmV0IGtleSBmb3IgdGhlIEpXVCBhbGdvbXMgdGhhdCBpcyBsb25nIGVub3VnaA==}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: stajprojesi
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-riza1907}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
