spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stajprojesi}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:riza1907}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9000

# JWT Ayarları
jwt.secret=${JWT_SECRET:VGhpcyBpcyBhIHZlcnkgc3VwZXIgc2VjcmV0IGtleSBmb3IgdGhlIEpXVCBhbGdvbXMgdGhhdCBpcyBsb25nIGVub3VnaA==}
jwt.expiration=36000000

# H2 Console (sadece development ortamında aktif edin)
spring.h2.console.enabled=false